Check nfp module ref count before trying to reload
When CoreNIC is installed as part of AOVS, and the CoreNIC package
is updated, ns-core-nic-setup will be executed again. However, in such a
case AOVS will have other kernel modules dependent on the nfp.ko module.
In which case it can't be unloaded and fails the setup procedure.

This could lead to the non-existance of udev rules.

However, when AOVS is running, CPP access will be available. So instead
of failing, check the ref count on the module and only fail if we don't
have CPP access with a non-zero ref count.

Similarly, we don't try to reload the module if the ref count is
non-zero. This will not succeed in any case.

Signed-off-by: Dirk van der Merwe <dirk.vandermerwe@netronome.com>
Acked-by: Pablo Cascón <pablo.cascon@netronome.com>

diff --git a/scripts/ns-core-nic-setup b/scripts/ns-core-nic-setup
--- a/scripts/ns-core-nic-setup
+++ b/scripts/ns-core-nic-setup
@@ -59,26 +59,21 @@ function check_and_load_driver() {
     # after DKMS install the nfp driver is not automatically
     # loaded. If nfp is loaded it is a previous version that we
     # have to unload. And then load the version we just installed
-    local nfp_net_drv_check
+    local nfp_net_drv_check ref_cnt dev_cpp
     lsmod | grep -wq "nfp" > /dev/null 2>&1
     nfp_net_drv_check=$?
+    ref_cnt=$(lsmod | awk '/^nfp / {print $3}')
 
-    if [ "$nfp_net_drv_check" -eq 0 ]; then
-        log "nfp already loaded"
-        log "Attempting to unload nfp driver"
-        rmmod nfp
-        if [ "$?" -ne 0 ]; then
-            log "Unload of nfp driver failed"
+    if [ "$ref_cnt" != "0" ]; then
+        log "Cannot unload nfp, ref count non-zero"
+        dev_cpp=$(cat /sys/module/nfp/parameters/nfp_dev_cpp 2>/dev/null)
+        if [ "${dev_cpp}" != "1" ]; then
+            log "nfp loaded without CPP access"
             log "ERROR"
             return 1
         fi
     else
-        # Unload nfp driver if loaded
-        local nfp_drv_check
-        lsmod | grep -wq "nfp" > /dev/null 2>&1
-        nfp_drv_check=$?
-
-        if [ "$nfp_drv_check" -eq 0 ]; then
+        if [ "$nfp_net_drv_check" -eq 0 ]; then
             log "nfp already loaded"
             log "Attempting to unload nfp driver"
             rmmod nfp
@@ -87,16 +82,32 @@ function check_and_load_driver() {
                 log "ERROR"
                 return 1
             fi
-        fi
-    fi
+        else
+            # Unload nfp driver if loaded
+            local nfp_drv_check
+            lsmod | grep -wq "nfp" > /dev/null 2>&1
+            nfp_drv_check=$?
 
-    log "Attempting to load nfp driver (userspace access only)"
-    modprobe nfp nfp_pf_netdev=0 nfp_dev_cpp=1
-    if [ "$?" -ne 0 ]; then
-        log "Auto load of nfp_net driver failed"
-        log "nfp driver is not loaded."
-        log "ERROR"
-        return 1
+            if [ "$nfp_drv_check" -eq 0 ]; then
+                log "nfp already loaded"
+                log "Attempting to unload nfp driver"
+                rmmod nfp
+                if [ "$?" -ne 0 ]; then
+                    log "Unload of nfp driver failed"
+                    log "ERROR"
+                    return 1
+                fi
+            fi
+        fi
+
+        log "Attempting to load nfp driver (userspace access only)"
+        modprobe nfp nfp_pf_netdev=0 nfp_dev_cpp=1
+        if [ "$?" -ne 0 ]; then
+            log "Auto load of nfp_net driver failed"
+            log "nfp driver is not loaded."
+            log "ERROR"
+            return 1
+        fi
     fi
 
     return 0
@@ -216,7 +227,12 @@ function err47_check() {
 }
 
 function reload_nfp_net() {
-    local nfp_net_drv_check
+    local nfp_net_drv_check ref_cnt
+
+    ref_cnt=$(lsmod | awk '/^nfp / {print $3}')
+    if [ "$ref_cnt" != "0" ]; then
+        return 0
+    fi
 
     lsmod | grep -wq "nfp" > /dev/null 2>&1
     nfp_net_drv_check=$?
